# Generated by Django 2.0.4 on 2018-06-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_num', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('work_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chenlin.WorkInfo')),
            ],
        ),
    ]
