# Generated by Django 2.0.4 on 2018-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chenlin', '0002_auto_20180607_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpic',
            name='picture',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
